def build(bld):
	tests = bld.path.ant_glob("*.cc")
	for l in bld.luas:
		for t in tests:
			bld.program(
				features = 'test',
				source = [t],
				target = l.uselib.lower() + '_test_' + t.name[:-3],
				includes = '..',
				install_path = None,
				use = [l.uselib, 'interlua_' + l.uselib.lower()],
			)
